name: Run test case

on: [push, pull_request]

jobs:
    run_test_case:
        runs-on: ubuntu-latest

        container:
            image: ghcr.io/emqx/emqx-builder/5.3-9:1.15.7-26.2.5-3-ubuntu22.04

        steps:
        - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

        - name: Compile
          run: |
            make dialyzer

        - name: Test
          run: |
            make test

        - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
          if: always()
          with:
            name: logs
            path: _build/test/logs
